GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON *.* TO 'wp'@'%' IDENTIFIED BY 'wp';
GRANT ALL PRIVILEGES ON *.* TO 'pma'@'%' IDENTIFIED BY 'pma';
FLUSH PRIVILEGES;
FLUSH HOSTS;
CREATE DATABASE wp;
CREATE DATABASE phpmyadmin;